--- #YAML:1.0
name:               Nginx-ReadBody
version:            0.03
abstract:           nginx web server embeded perl module to read and evaluate a request body
author:
    - Daniel Podolsky <tpaba@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    nginx:  0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
